server:
  port: 7777
spring:
  datasource:
    username: postgres
    password: 1
    url: jdbc:postgresql://localhost:5432/login
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true